name: Test React Project
on: push # 1. On a push event, trigger the jobs below

jobs:
  main-workflow: # 2. Specify Name of the Job that we have under the Workflow

    runs-on: ubuntu-latest # 3. Define The runner that we will use to execute the steps
    steps:
        
        - name: Fetch the code from Repository
          uses: actions/checkout@v3

        - name: Install NodeJS
          uses: actions/setup-node@v3

          with:
            node-version: '23'

        - name: Install Dependencies
          run: npm ci
    
        - name: Run Unit Tests
          run: npm test